### ISSUE TITLE
Method UpdateCredentials(RasPreSharedKey key, string value) couldn't work,inoperative

### ISSUE THREAD

**Issue by GitCod-Man** [DotRas/DotRas#111]
hello, i'm creating my vpn client for windows7 and win10, i use c# and vs2019,
my code like this:
  RasEntry entry = RasEntry.CreateVpnEntry("MyVPNConnection3", "190.92.10.10", RasVpnStrategy.L2tpOnly, RasDevice.GetDeviceByName("(L2TP)", RasDeviceType.Vpn));

              

                pbk.Entries.Add(entry);

                entry.Options.PreviewDomain = false;
                entry.Options.ShowDialingProgress = false;
                entry.Options.PromoteAlternates = false;
                entry.Options.DoNotNegotiateMultilink = false;

                entry.Options.UsePreSharedKey = true;
               // Entry.UpdateCredentials(RasPreSharedKey.Client, _preSharedKey);

                bool r = entry.UpdateCredentials(RasPreSharedKey.Client, "AAAABBBBCCCCDDDD");

the r is True,  the vpn connection is created,but the L2tp preSharedKey has no effective;
on the vpn connection advanced settings, it still use with identity authentication but not use PreSharedKey, why ?
can u help me ?Thanks!

**Comment by jeff-winn** [comment]
V1 is not being supported by this repository.
