### ISSUE TITLE
Can not find RasPhoneBook and RasEntry

### ISSUE THREAD

**Issue by rebelhn** [DotRas/DotRas#112]
I'm using 2.0.0 for Win10 but can not find RasEntry and RasPhoneBook to create connect from client.

**Comment by shuum** [comment]
I join the question, how in 2.0 to do for example `RasEntry.CreateVpnEntry`? Great thnx!

**Comment by jeff-winn** [comment]
2.0 does not yet have this functionality. This is already being tracked by #22
