### ISSUE TITLE
Prioritize custom DNS server over VPN DNS servers on IKEv2 interface

### ISSUE THREAD

**Issue by jmithy** [DotRas/DotRas#113]
I want to prioritize a custom DNS server over the VPN DNS servers on my IKEv2 interface. Currently, the custom DNS server is listed last in the DNSAddress of the Network Interface. Is there a way to make the custom DNS server appear first in the list? I would appreciate your assistance in achieving this. I'm currently adding the custom DNS server using the entry.DnsAddress = "some dns address"

**Comment by jeff-winn** [comment]
The V1 version is not supported on this repository and the V2 version does not have support for editing entries.
